import csv


def parse_answers(csv_file_path):
    results = []
    with open(csv_file_path, newline='', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            results.append({
                "book_id": int(row["book_id"]),
                "file_id": row["file_id"]
            })
    return results


answers = parse_answers("math_book_ids.json")
print(answers)

book_datas = [{'book_id': 21, 'name': 'Sonning boʻluvchilari 2', 'question_number': 1, 'answer': 'c'},
              {'book_id': 21, 'name': 'Sonning boʻluvchilari 2', 'question_number': 2, 'answer': 'a'},
              {'book_id': 21, 'name': 'Sonning boʻluvchilari 2', 'question_number': 3, 'answer': 'b'},
              {'book_id': 21, 'name': 'Sonning boʻluvchilari 2', 'question_number': 4, 'answer': 'b'},
              {'book_id': 21, 'name': 'Sonning boʻluvchilari 2', 'question_number': 5, 'answer': 'b'},
              {'book_id': 21, 'name': 'Sonning boʻluvchilari 2', 'question_number': 6, 'answer': 'c'},
              {'book_id': 21, 'name': 'Sonning boʻluvchilari 2', 'question_number': 7, 'answer': 'c'},
              {'book_id': 21, 'name': 'Sonning boʻluvchilari 2', 'question_number': 8, 'answer': 'a'},
              {'book_id': 21, 'name': 'Sonning boʻluvchilari 2', 'question_number': 9, 'answer': 'b'},
              {'book_id': 21, 'name': 'Sonning boʻluvchilari 2', 'question_number': 10, 'answer': 'd'},
              {'book_id': 21, 'name': 'Sonning boʻluvchilari 2', 'question_number': 11, 'answer': 'c'},
              {'book_id': 21, 'name': 'Sonning boʻluvchilari 2', 'question_number': 12, 'answer': 'a'},
              {'book_id': 21, 'name': 'Sonning boʻluvchilari 2', 'question_number': 13, 'answer': 'c'},
              {'book_id': 21, 'name': 'Sonning boʻluvchilari 2', 'question_number': 14, 'answer': 'c'},
              {'book_id': 21, 'name': 'Sonning boʻluvchilari 2', 'question_number': 15, 'answer': 'd'},
              {'book_id': 21, 'name': 'Sonning boʻluvchilari 2', 'question_number': 16, 'answer': 'c'},
              {'book_id': 21, 'name': 'Sonning boʻluvchilari 2', 'question_number': 17, 'answer': 'b'},
              {'book_id': 21, 'name': 'Sonning boʻluvchilari 2', 'question_number': 18, 'answer': 'b'},
              {'book_id': 21, 'name': 'Sonning boʻluvchilari 2', 'question_number': 19, 'answer': 'a'},
              {'book_id': 21, 'name': 'Sonning boʻluvchilari 2', 'question_number': 20, 'answer': 'd'},
              {'book_id': 41, 'name': "Qoldiqli bo'lish", 'question_number': 1, 'answer': 'a'},
              {'book_id': 41, 'name': "Qoldiqli bo'lish", 'question_number': 2, 'answer': 'd'},
              {'book_id': 41, 'name': "Qoldiqli bo'lish", 'question_number': 3, 'answer': 'a'},
              {'book_id': 41, 'name': "Qoldiqli bo'lish", 'question_number': 4, 'answer': 'c'},
              {'book_id': 41, 'name': "Qoldiqli bo'lish", 'question_number': 5, 'answer': 'd'},
              {'book_id': 41, 'name': "Qoldiqli bo'lish", 'question_number': 6, 'answer': 'd'},
              {'book_id': 41, 'name': "Qoldiqli bo'lish", 'question_number': 7, 'answer': 'b'},
              {'book_id': 41, 'name': "Qoldiqli bo'lish", 'question_number': 8, 'answer': 'b'},
              {'book_id': 41, 'name': "Qoldiqli bo'lish", 'question_number': 9, 'answer': 'b'},
              {'book_id': 41, 'name': "Qoldiqli bo'lish", 'question_number': 10, 'answer': 'a'},
              {'book_id': 41, 'name': "Qoldiqli bo'lish", 'question_number': 11, 'answer': 'c'},
              {'book_id': 41, 'name': "Qoldiqli bo'lish", 'question_number': 12, 'answer': 'a'},
              {'book_id': 41, 'name': "Qoldiqli bo'lish", 'question_number': 13, 'answer': 'c'},
              {'book_id': 41, 'name': "Qoldiqli bo'lish", 'question_number': 14, 'answer': 'c'},
              {'book_id': 41, 'name': "Qoldiqli bo'lish", 'question_number': 15, 'answer': 'd'},
              {'book_id': 41, 'name': "Qoldiqli bo'lish", 'question_number': 16, 'answer': 'a'},
              {'book_id': 41, 'name': "Qoldiqli bo'lish", 'question_number': 17, 'answer': 'b'},
              {'book_id': 41, 'name': "Qoldiqli bo'lish", 'question_number': 18, 'answer': 'b'},
              {'book_id': 41, 'name': "Qoldiqli bo'lish", 'question_number': 19, 'answer': 'b'},
              {'book_id': 41, 'name': "Qoldiqli bo'lish", 'question_number': 20, 'answer': 'c'},
              {'book_id': 61, 'name': "Qoldiqli bo'lish 2", 'question_number': 1, 'answer': 'c'},
              {'book_id': 61, 'name': "Qoldiqli bo'lish 2", 'question_number': 2, 'answer': 'b'},
              {'book_id': 61, 'name': "Qoldiqli bo'lish 2", 'question_number': 3, 'answer': 'd'},
              {'book_id': 61, 'name': "Qoldiqli bo'lish 2", 'question_number': 4, 'answer': 'c'},
              {'book_id': 61, 'name': "Qoldiqli bo'lish 2", 'question_number': 5, 'answer': 'c'},
              {'book_id': 61, 'name': "Qoldiqli bo'lish 2", 'question_number': 6, 'answer': 'b'},
              {'book_id': 61, 'name': "Qoldiqli bo'lish 2", 'question_number': 7, 'answer': 'd'},
              {'book_id': 61, 'name': "Qoldiqli bo'lish 2", 'question_number': 8, 'answer': 'b'},
              {'book_id': 61, 'name': "Qoldiqli bo'lish 2", 'question_number': 9, 'answer': 'c'},
              {'book_id': 61, 'name': "Qoldiqli bo'lish 2", 'question_number': 10, 'answer': 'c'},
              {'book_id': 61, 'name': "Qoldiqli bo'lish 2", 'question_number': 11, 'answer': 'b'},
              {'book_id': 61, 'name': "Qoldiqli bo'lish 2", 'question_number': 12, 'answer': 'b'},
              {'book_id': 61, 'name': "Qoldiqli bo'lish 2", 'question_number': 13, 'answer': 'd'},
              {'book_id': 61, 'name': "Qoldiqli bo'lish 2", 'question_number': 14, 'answer': 'c'},
              {'book_id': 61, 'name': "Qoldiqli bo'lish 2", 'question_number': 15, 'answer': 'd'},
              {'book_id': 61, 'name': "Qoldiqli bo'lish 2", 'question_number': 16, 'answer': 'a'},
              {'book_id': 61, 'name': "Qoldiqli bo'lish 2", 'question_number': 17, 'answer': 'b'},
              {'book_id': 61, 'name': "Qoldiqli bo'lish 2", 'question_number': 18, 'answer': 'a'},
              {'book_id': 61, 'name': "Qoldiqli bo'lish 2", 'question_number': 19, 'answer': 'a'},
              {'book_id': 61, 'name': "Qoldiqli bo'lish 2", 'question_number': 20, 'answer': 'b'},
              {'book_id': 81, 'name': "Tub ko'paytiruvchilar", 'question_number': 1, 'answer': 'a'},
              {'book_id': 81, 'name': "Tub ko'paytiruvchilar", 'question_number': 2, 'answer': 'c'},
              {'book_id': 81, 'name': "Tub ko'paytiruvchilar", 'question_number': 3, 'answer': 'b'},
              {'book_id': 81, 'name': "Tub ko'paytiruvchilar", 'question_number': 4, 'answer': 'a'},
              {'book_id': 81, 'name': "Tub ko'paytiruvchilar", 'question_number': 5, 'answer': 'b'},
              {'book_id': 81, 'name': "Tub ko'paytiruvchilar", 'question_number': 6, 'answer': 'b'},
              {'book_id': 81, 'name': "Tub ko'paytiruvchilar", 'question_number': 7, 'answer': 'b'},
              {'book_id': 81, 'name': "Tub ko'paytiruvchilar", 'question_number': 8, 'answer': 'c'},
              {'book_id': 81, 'name': "Tub ko'paytiruvchilar", 'question_number': 9, 'answer': 'b'},
              {'book_id': 81, 'name': "Tub ko'paytiruvchilar", 'question_number': 10, 'answer': 'b'},
              {'book_id': 81, 'name': "Tub ko'paytiruvchilar", 'question_number': 11, 'answer': 'b'},
              {'book_id': 81, 'name': "Tub ko'paytiruvchilar", 'question_number': 12, 'answer': 'c'},
              {'book_id': 81, 'name': "Tub ko'paytiruvchilar", 'question_number': 13, 'answer': 'b'},
              {'book_id': 81, 'name': "Tub ko'paytiruvchilar", 'question_number': 14, 'answer': 'c'},
              {'book_id': 81, 'name': "Tub ko'paytiruvchilar", 'question_number': 15, 'answer': 'c'},
              {'book_id': 81, 'name': "Tub ko'paytiruvchilar", 'question_number': 16, 'answer': 'b'},
              {'book_id': 81, 'name': "Tub ko'paytiruvchilar", 'question_number': 17, 'answer': 'b'},
              {'book_id': 81, 'name': "Tub ko'paytiruvchilar", 'question_number': 18, 'answer': 'a'},
              {'book_id': 81, 'name': "Tub ko'paytiruvchilar", 'question_number': 19, 'answer': 'd'},
              {'book_id': 81, 'name': "Tub ko'paytiruvchilar", 'question_number': 20, 'answer': 'b'},
              {'book_id': 101, 'name': 'Oddiy kasrlar', 'question_number': 1, 'answer': 'd'},
              {'book_id': 101, 'name': 'Oddiy kasrlar', 'question_number': 2, 'answer': 'a'},
              {'book_id': 101, 'name': 'Oddiy kasrlar', 'question_number': 3, 'answer': 'a'},
              {'book_id': 101, 'name': 'Oddiy kasrlar', 'question_number': 4, 'answer': 'c'},
              {'book_id': 101, 'name': 'Oddiy kasrlar', 'question_number': 5, 'answer': 'd'},
              {'book_id': 101, 'name': 'Oddiy kasrlar', 'question_number': 6, 'answer': 'a'},
              {'book_id': 101, 'name': 'Oddiy kasrlar', 'question_number': 7, 'answer': 'd'},
              {'book_id': 101, 'name': 'Oddiy kasrlar', 'question_number': 8, 'answer': 'a'},
              {'book_id': 101, 'name': 'Oddiy kasrlar', 'question_number': 9, 'answer': 'a'},
              {'book_id': 101, 'name': 'Oddiy kasrlar', 'question_number': 10, 'answer': 'a'},
              {'book_id': 101, 'name': 'Oddiy kasrlar', 'question_number': 11, 'answer': 'c'},
              {'book_id': 101, 'name': 'Oddiy kasrlar', 'question_number': 12, 'answer': 'a'},
              {'book_id': 101, 'name': 'Oddiy kasrlar', 'question_number': 13, 'answer': 'd'},
              {'book_id': 101, 'name': 'Oddiy kasrlar', 'question_number': 14, 'answer': 'b'},
              {'book_id': 101, 'name': 'Oddiy kasrlar', 'question_number': 15, 'answer': 'c'},
              {'book_id': 101, 'name': 'Oddiy kasrlar', 'question_number': 16, 'answer': 'b'},
              {'book_id': 101, 'name': 'Oddiy kasrlar', 'question_number': 17, 'answer': 'c'},
              {'book_id': 101, 'name': 'Oddiy kasrlar', 'question_number': 18, 'answer': 'a'},
              {'book_id': 101, 'name': 'Oddiy kasrlar', 'question_number': 19, 'answer': 'b'},
              {'book_id': 101, 'name': 'Oddiy kasrlar', 'question_number': 20, 'answer': 'b'}]

book_ids = [{'book_id': 1, 'file_id': 'BQACAgIAAxkBAAIC42gYwGAUVuxgZywWh2fvfWtuB0pRAAItbAACGd-oSLXiI38vBwlzNgQ'},
            {'book_id': 21, 'file_id': 'BQACAgIAAxkBAAIETWgZgwZqtWJQM0U7ll5IaeSkxs11AAJ7bAACWqHJSHLG-D0N5daFNgQ'},
            {'book_id': 41, 'file_id': 'BQACAgIAAxkBAAIG7Wga2XGdndtEuE-JwDUXJDkrQkaYAALhbQACvxLYSED6MtbIqI8SNgQ'},
            {'book_id': 61, 'file_id': 'BQACAgIAAxkBAAIJAmgcNQdV85JMVubaLQ2dvkKKtzYTAAJRewACvYzgSGI8DCbAI2sAATYE'},
            {'book_id': 81, 'file_id': 'BQACAgIAAxkBAAIC42gYwGAUVuxgZywWh2fvfWtuB0pRAAItbAACGd-oSLXiI38vBwlzNgQ'},
            {'book_id': 101, 'file_id': 'BQACAgIAAxkBAAILb2gdkZVeMAUOQ1NRaWcgDuxo9GNoAAJacgACvYzoSDEt62tZZIwJNgQ'}]
